# Generated by Django 4.2.2 on 2023-07-13 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapeletaPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('codigo_papeleta', models.CharField(max_length=10, unique=True)),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20)),
                ('ingenieria', models.CharField(max_length=70)),
                ('cuatrimestre', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=40)),
                ('fecha_prestamo', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
