# Generated by Django 4.2.2 on 2023-07-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Papeleta', '0003_alter_papeletaprestamo_codigo_papeleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papeletaprestamo',
            name='codigo_papeleta',
            field=models.CharField(default=True, max_length=10, unique=True),
        ),
    ]
