# Generated by Django 4.2.2 on 2023-07-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Usuario', max_length=20),
        ),
    ]
